### PR TITLE
[Change] Allow modifications to zone_info query parameters

### PR DESCRIPTION
**Pull request by lpalgarvio**
based on patch https://github.com/linuxhq/ansible-collection-cloudflare/commit/968a71731301805597d2027a8130fe49a23eebc4
issue at https://github.com/linuxhq/ansible-collection-cloudflare/issues/1

### CODE REVIEW

**Comment by tkimball83** [comment]
Those variables need to be added to the role defaults and the README updated accordingly.

**Comment by lpalgarvio** [comment]
yes, just spotted that

**Comment by lpalgarvio** [comment]
ready @tkimball83

**Comment by lpalgarvio** [comment]
tested with 1st and 2nd page, paging 20 results
then only 1st page with 50 results

**Comment by tkimball83** [comment]
Please add those variables to the README of the role as well.  Thanks!

**Comment by lpalgarvio** [comment]
sorry missed that too.
probably best to squash and merge into a single commit as "[Change] Allow modifications to zone_info query parameters"

**Comment by lpalgarvio** [comment]
just added the README change

**Pull request merged**
